packages:
  - 'packages/*'

catalogs:
  build:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@shikijs/markdown-it': ^3.7.0
    '@unocss/eslint-config': ^66.3.2
    '@vitejs/plugin-vue': ^6.0.0
    beasties: ^0.3.4
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.44.1
    rollup-plugin-visualizer: ^6.0.3
    shiki: ^3.7.0
    unocss: ^66.3.2
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^28.3.1
    unplugin-vue-router: ^0.12.0
    vite: ^7.0.0
    vite-plugin-compression2: ^2.2.0
    vite-plugin-html: ^3.2.2
    vite-plugin-inspect: ^11.2.0
    vite-plugin-pwa: ^1.0.0
    vite-plugin-vue-devtools: ^7.7.7
  dev:
    '@antfu/eslint-config': ^4.16.1
    '@iconify-json/carbon': ^1.2.10
    '@vue-macros/volar': ^3.0.0-beta.15
    '@vue/test-utils': ^2.4.6
    cypress: ^14.5.0
    cypress-vite: ^1.6.0
    eslint: ^9.29.0
    eslint-plugin-cypress: ^5.1.0
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.2.4
    vue-tsc: ^2.2.10
  frontend:
    '@unhead/vue': ^2.0.11
    '@unocss/reset': ^66.3.2
    '@vueuse/core': ^13.4.0
    nprogress: ^0.2.0
    pinia: ^3.0.3
    vue: ^3.5.17
    vue-i18n: ^11.1.7
    vue-router: ^4.5.1
  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
