/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    WtDialog: typeof import('./components/wt-dialog/index.vue')['default']
    WtDock: typeof import('./components/wt-dock/index.vue')['default']
    WtList: typeof import('./pages/browser/components/wt-list/index.vue')['default']
  }
}
