/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/browser/': RouteRecordInfo<'/browser/', '/browser', Record<never, never>, Record<never, never>>,
    '/browser/components/wt-list/': RouteRecordInfo<'/browser/components/wt-list/', '/browser/components/wt-list', Record<never, never>, Record<never, never>>,
    '/folder/': RouteRecordInfo<'/folder/', '/folder', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/widgets/quick-nav/': RouteRecordInfo<'/home/widgets/quick-nav/', '/home/widgets/quick-nav', Record<never, never>, Record<never, never>>,
    '/home/widgets/search-box/': RouteRecordInfo<'/home/widgets/search-box/', '/home/widgets/search-box', Record<never, never>, Record<never, never>>,
    '/home/widgets/time-displayer/': RouteRecordInfo<'/home/widgets/time-displayer/', '/home/widgets/time-displayer', Record<never, never>, Record<never, never>>,
    '/home/widgets/workspace-create-dialog/': RouteRecordInfo<'/home/widgets/workspace-create-dialog/', '/home/widgets/workspace-create-dialog', Record<never, never>, Record<never, never>>,
  }
}
